[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "squid"
version = "0.1.0"
description = "OANDA data synchronization tool"
requires-python = ">=3.8"